"""Course import: lessons + session cookies sent by the browser extension become ingest jobs.

The extension runs inside the user's logged-in browser, scans the course pages for embedded players, and posts
{course, lessons, cookies}. We write the cookies to a Netscape-format file (what yt-dlp expects), create a
"course" collection, and queue one ingest job per lesson video with the lesson page as Referer (domain-locked
Vimeo/Wistia embeds require it).
"""
from __future__ import annotations

import logging
import re
import time
from typing import Any
from urllib.parse import urlparse

from . import db, jobs
from .config import settings

log = logging.getLogger(__name__)

# hosts whose embeds yt-dlp can fetch; anything else is tried as a generic URL
PLAYER_HOSTS = ("loom.com", "vimeo.com", "wistia", "youtube.com", "youtu.be", "youtube-nocookie.com", "vidyard.com",
                "bunny.net", "mediadelivery.net", "cloudfront.net", "muxplayer", "stream.mux.com", "jwplayer", "kajabi")


def write_cookie_file(cookies: list[dict[str, Any]], name: str) -> str:
    """Netscape cookies.txt from chrome.cookies.getAll() objects."""
    d = settings.data_dir / "cookies"
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{name}.txt"
    lines = ["# Netscape HTTP Cookie File", "# generated by Neuro Search course import", ""]
    for c in cookies:
        dom = str(c.get("domain") or "")
        if not dom or not c.get("name"):
            continue
        include_sub = "TRUE" if dom.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expirationDate") or c.get("expires") or (time.time() + 86400 * 30))
        lines.append("\t".join([dom, include_sub, str(c.get("path") or "/"), secure, str(exp), str(c["name"]), str(c.get("value") or "")]))
    path.write_text("\n".join(lines) + "\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return str(path)


def normalise_embed(url: str) -> str:
    """Turn embed/player URLs into the canonical page yt-dlp handles best."""
    u = url.strip()
    m = re.search(r"loom\.com/(?:embed|share)/([A-Za-z0-9]+)", u)
    if m:
        return f"https://www.loom.com/share/{m.group(1)}"
    m = re.search(r"player\.vimeo\.com/video/(\d+)(?:\?h=([A-Za-z0-9]+))?", u)
    if m:
        return f"https://vimeo.com/{m.group(1)}" + (f"/{m.group(2)}" if m.group(2) else "")
    m = re.search(r"youtube(?:-nocookie)?\.com/embed/([A-Za-z0-9_-]{11})", u)
    if m:
        return f"https://www.youtube.com/watch?v={m.group(1)}"
    return u


def import_course(project_id: str, course: dict[str, Any], lessons: list[dict[str, Any]],
                  cookies: list[dict[str, Any]] | None) -> dict[str, Any]:
    if not db.get_project(project_id):
        raise RuntimeError("project not found")
    title = (course.get("title") or urlparse(course.get("url", "")).netloc or "Course").strip()[:150]
    coll = db.upsert_collection("course", course.get("url") or title, course.get("url"), title)
    db.add_project_collections(project_id, [coll["id"]])
    cookies_file = write_cookie_file(cookies, coll["id"]) if cookies else None

    queued, skipped, no_video = 0, 0, []
    for i, les in enumerate(lessons, 1):
        vids = [normalise_embed(v) for v in (les.get("video_urls") or []) if isinstance(v, str) and v.startswith("http")]
        if not vids:
            no_video.append(les.get("title") or les.get("page_url"))
            continue
        module = (les.get("module") or "").strip()
        lesson_title = (les.get("title") or f"Lesson {i}").strip()
        full_title = f"{module} › {lesson_title}" if module else lesson_title
        for j, v in enumerate(vids):
            t = full_title if len(vids) == 1 else f"{full_title} ({j + 1})"
            jobs.enqueue("ingest_url", {
                "url": v, "tags": [], "project_id": project_id, "force": False,
                "cookies_file": cookies_file, "referer": les.get("page_url"), "title": t, "collection_id": coll["id"],
            })
            queued += 1
    return {"collection_id": coll["id"], "title": title, "lessons": len(lessons), "queued": queued,
            "skipped": skipped, "no_video": no_video, "cookies": bool(cookies_file)}
