"""Course import: lessons + session cookies sent by the browser extension become ingest jobs.

The extension runs inside the user's logged-in browser, scans the course pages for embedded players, and posts
{course, lessons, cookies}. We write the cookies to a Netscape-format file (what yt-dlp expects), create a
"course" collection, and queue one ingest job per lesson video with the lesson page as Referer (domain-locked
Vimeo/Wistia embeds require it).
"""
from __future__ import annotations

import logging
import re
import time
from typing import Any
from urllib.parse import urlparse

from . import db, jobs
from .config import settings

log = logging.getLogger(__name__)

# hosts whose embeds yt-dlp can fetch; anything else is tried as a generic URL
PLAYER_HOSTS = ("loom.com", "vimeo.com", "wistia", "youtube.com", "youtu.be", "youtube-nocookie.com", "vidyard.com",
                "bunny.net", "mediadelivery.net", "cloudfront.net", "muxplayer", "stream.mux.com", "jwplayer", "kajabi")


def write_cookie_file(cookies: list[dict[str, Any]], name: str) -> str:
    """Netscape cookies.txt from chrome.cookies.getAll() objects."""
    d = settings.data_dir / "cookies"
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{name}.txt"
    lines = ["# Netscape HTTP Cookie File", "# generated by Neuro Search course import", ""]
    for c in cookies:
        dom = str(c.get("domain") or "")
        if not dom or not c.get("name"):
            continue
        include_sub = "TRUE" if dom.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expirationDate") or c.get("expires") or (time.time() + 86400 * 30))
        lines.append("\t".join([dom, include_sub, str(c.get("path") or "/"), secure, str(exp), str(c["name"]), str(c.get("value") or "")]))
    path.write_text("\n".join(lines) + "\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return str(path)


def normalise_embed(url: str) -> str:
    """Turn embed/player URLs into the canonical page yt-dlp handles best."""
    u = url.strip()
    m = re.search(r"loom\.com/(?:embed|share)/([A-Za-z0-9]+)", u)
    if m:
        return f"https://www.loom.com/share/{m.group(1)}"
    m = re.search(r"player\.vimeo\.com/video/(\d+)(?:\?h=([A-Za-z0-9]+))?", u)
    if m:
        return f"https://vimeo.com/{m.group(1)}" + (f"/{m.group(2)}" if m.group(2) else "")
    m = re.search(r"youtube(?:-nocookie)?\.com/embed/([A-Za-z0-9_-]{11})", u)
    if m:
        return f"https://www.youtube.com/watch?v={m.group(1)}"
    return u


def add_page_videos(project_id: str, source_id: str, cookies: list[dict[str, Any]] | None = None,
                    urls: list[str] | None = None) -> dict[str, Any]:
    """Queue the videos a captured page embeds — the explicit, priced half of the capture (0.63.16).

    Kyle captured a lesson with "Send this page": the notes arrived, the Loom video did not. `ingest_webpage` now
    RECORDS the embeds (`webpage.video_embeds`) and this is how they become sources — a separate verb, because a
    video means a download and a transcription, and nothing here spends without being asked.

    Reuses the course importer's machinery exactly: the same `write_cookie_file` (a private Loom needs the user's
    session), the same `normalise_embed`, the same `ingest_url` job, and the page's own URL as the referer, which
    Loom checks on an embed. No second path."""
    if not db.get_project(project_id):
        raise RuntimeError("project not found")
    src = db.get_source(source_id)
    if not src:
        raise RuntimeError("source not found")
    found = [u for u in (urls or db.video_embeds_of(source_id)) if isinstance(u, str) and u.startswith("http")]
    if not found:
        return {"queued": 0, "videos": [], "why": "no video embed was recorded for that page"}
    # Already in the library? Then say so rather than queueing a job that will dedupe silently (0.63.17).
    have = db.sources_for_urls([normalise_embed(u) for u in found])
    fresh = [u for u in found if normalise_embed(u) not in have]
    if not fresh:
        return {"queued": 0, "videos": [], "already": list(have.values()),
                "why": f"already added — {len(have)} video{'s' if len(have) != 1 else ''} from this page is in the library"}
    found = fresh
    page_url = src.get("url") or ""
    title = (src.get("title") or "page").strip()[:120]
    coll = db.upsert_collection("course", page_url or title, page_url, title)
    if project_id:
        db.add_project_collections(project_id, [coll["id"]])
    cookies_file = write_cookie_file(cookies, coll["id"]) if cookies else None
    queued = []
    for j, v in enumerate(found):
        t = title if len(found) == 1 else f"{title} ({j + 1})"
        jobs.enqueue("ingest_url", {"url": normalise_embed(v), "tags": [], "project_id": project_id, "force": False,
                                    "cookies_file": cookies_file, "referer": page_url, "title": t,
                                    "collection_id": coll["id"]})
        queued.append(normalise_embed(v))
    log.info("queued %d embedded video(s) from %s", len(queued), source_id[:8])
    return {"queued": len(queued), "videos": queued, "collection_id": coll["id"], "cookies": bool(cookies_file)}


def import_course(project_id: str, course: dict[str, Any], lessons: list[dict[str, Any]],
                  cookies: list[dict[str, Any]] | None) -> dict[str, Any]:
    """mission CS, amendment #11: a video can be the lesson for more than one row (a shared intro, a recap linked
    from two modules) — acquire it once, but keep telling the truth about every lesson that uses it. A duplicate
    ACQUISITION is never a duplicate MEMBERSHIP, so lessons are grouped by their normalised video url before any
    job is enqueued, `sources_for_urls` is asked (amendment: derived truth, no second "added" flag) so an already-
    downloaded video is reported, not re-queued, and every url referenced by more than one lesson is named in
    `shared` even though it only produced one job.

    amendment #10: normalise_embed only canonicalises the providers scan-lib.js's IDENTITY table treats as stable
    (Loom/Vimeo/YouTube) — a direct/CDN url is passed through untouched and grouped on its literal string, which is
    conservative (it may miss a dedupe a signed-url provider would allow) rather than wrong."""
    if not db.get_project(project_id):
        raise RuntimeError("project not found")
    title = (course.get("title") or urlparse(course.get("url", "")).netloc or "Course").strip()[:150]
    coll = db.upsert_collection("course", course.get("url") or title, course.get("url"), title)
    db.add_project_collections(project_id, [coll["id"]])
    cookies_file = write_cookie_file(cookies, coll["id"]) if cookies else None

    by_url: dict[str, dict[str, Any]] = {}   # normalised video url -> {referer, titles: [lesson titles using it]}
    # CS7: a lesson's DOCUMENTS (the scanner's `attachments`: a PDF/DOCX/XLSX link, a Drive/Docs/Sheets share link)
    # are acquired too — through `ingest_document_url`, never through a video job — keyed on the link as the page
    # shows it, so a document two lessons both link is fetched once and named for both, exactly like a video.
    docs: dict[str, dict[str, Any]] = {}     # attachment url -> {referer, titles, name}
    no_video = []
    nothing = []
    for i, les in enumerate(lessons, 1):
        vids = [normalise_embed(v) for v in (les.get("video_urls") or []) if isinstance(v, str) and v.startswith("http")]
        atts = [a for a in (les.get("attachments") or []) if isinstance(a, dict) and isinstance(a.get("url"), str) and a["url"].startswith("http")]
        module = (les.get("module") or "").strip()
        lesson_title = (les.get("title") or f"Lesson {i}").strip()
        full_title = f"{module} › {lesson_title}" if module else lesson_title
        if not vids:
            no_video.append(les.get("title") or les.get("page_url"))
        if not vids and not atts:
            nothing.append(les.get("title") or les.get("page_url"))
            continue
        for v in vids:
            entry = by_url.setdefault(v, {"referer": les.get("page_url"), "titles": []})
            entry["titles"].append(full_title)
        for a in atts:
            entry = docs.setdefault(a["url"], {"referer": les.get("page_url"), "titles": [], "name": (a.get("title") or "").strip()})
            entry["titles"].append(full_title)

    have = db.sources_for_urls(list(by_url) + list(docs))
    shared = [u for u, e in by_url.items() if len(e["titles"]) > 1]

    queued = 0
    for u, e in by_url.items():
        if u in have:
            continue
        titles = e["titles"]
        t = titles[0] if len(titles) == 1 else f"{titles[0]} (+{len(titles) - 1} more lesson{'s' if len(titles) > 2 else ''})"
        jobs.enqueue("ingest_url", {
            "url": u, "tags": [], "project_id": project_id, "force": False,
            "cookies_file": cookies_file, "referer": e["referer"], "title": t, "collection_id": coll["id"],
        })
        queued += 1

    documents = 0
    for u, e in docs.items():
        if u in have:
            continue
        titles = e["titles"]
        t = titles[0] if len(titles) == 1 else f"{titles[0]} (+{len(titles) - 1} more lesson{'s' if len(titles) > 2 else ''})"
        if e["name"] and e["name"].lower() not in t.lower():
            t = f"{t} — {e['name']}"[:200]
        # no cookies: a document host is not a video host; a file that needs a sign-in is reported, not smuggled
        jobs.enqueue("ingest_url", {
            "url": u, "tags": [], "project_id": project_id, "force": False,
            "referer": e["referer"], "title": t, "collection_id": coll["id"],
        })
        documents += 1

    return {"collection_id": coll["id"], "title": title, "lessons": len(lessons), "queued": queued, "documents": documents,
            "already_present": [have[u] for u in list(by_url) + list(docs) if u in have], "shared": shared, "no_video": no_video,
            "nothing": nothing, "cookies": bool(cookies_file)}
